###############
### newgame ###
###############

POST http://localhost:8080/games
Content-Type: application/json

{"code": "newgame", "playerNumber":  3}

###

POST http://localhost:8080/games/newgame/players
Content-Type: application/json

{"playerName":  "Lorem"}

###  cderrnftgwrewsvisfexgbrnqb

POST http://localhost:8080/games/newgame/players
Content-Type: application/json

{"playerName":  "Ipsum"}

###  whdcxiposskxbzlqcjtvpjcqwx

POST http://localhost:8080/games/newgame/players
Content-Type: application/json

{"playerName":  "Dolor"}

###  qpfiiqnbenjiafzzludsazazvj

POST http://localhost:8080/games/newgame/inputs
Content-Type: application/json

{"playerCode": "odqmflgxsdejustfnnpxlecwoh", "input": "Scandinavie"}

###

POST http://localhost:8080/games/newgame/inputs
Content-Type: application/json

{"playerCode": "qodbfxswnyfwzkfktaxwtjxjxb", "input": "Ukraine"}

###

POST http://localhost:8080/games/newgame/inputs
Content-Type: application/json

{"playerCode": "hdbvcaohdfgxxbpuswcwnnfzcc", "input": "Islande"}

###


#############
### game2 ###
#############

POST http://localhost:8080/games
Content-Type: application/json

{"code": "game2", "playerNumber":  3}

###

POST http://localhost:8080/games/game2
Content-Type: application/json

{"playerName":  "Lorem1"}

###

POST http://localhost:8080/games/game2
Content-Type: application/json

{"playerName":  "Ipsum1"}

###

POST http://localhost:8080/games/game2
Content-Type: application/json

{"playerName":  "Dolor1"}

###

POST http://localhost:8080/games/game2/input
Content-Type: application/json

{"playerName": "Lorem1", "input": "Europe-du-Nord"}

###
