###############
### newgame ###
###############

POST http://localhost:8080/games
Content-Type: application/json

{"code": "newgame", "playerNumber":  3}

###

POST http://localhost:8080/games/newgame/players
Content-Type: application/json

{"playerName":  "Lorem", "wishedCode": "lorem"}

###

POST http://localhost:8080/games/newgame/players
Content-Type: application/json

{"playerName":  "Ipsum", "wishedCode": "ipsum"}

###

POST http://localhost:8080/games/newgame/players
Content-Type: application/json

{"playerName":  "Dolor", "wishedCode": "dolor"}

###

POST http://localhost:8080/games/newgame/inputs
Content-Type: application/json

{"playerCode": "lorem", "input": "Islande"}

###

POST http://localhost:8080/games/newgame/inputs
Content-Type: application/json

{"playerCode": "ipsum", "input": "Ukraine"}

###

POST http://localhost:8080/games/newgame/inputs
Content-Type: application/json

{"playerCode": "dolor", "input": "Grande-Bretagne"}

###


###############
### oldgame ###
###############

POST http://localhost:8080/games
Content-Type: application/json

{"code": "oldgame", "playerNumber":  3}

###

POST http://localhost:8080/games/oldgame/players
Content-Type: application/json

{"playerName":  "Sit", "wishedCode": "sit"}

###

POST http://localhost:8080/games/oldgame/players
Content-Type: application/json

{"playerName":  "Amet", "wishedCode": "amet"}

###

POST http://localhost:8080/games/oldgame/players
Content-Type: application/json

{"playerName":  "Donec", "wishedCode": "donec"}

###

POST http://localhost:8080/games/oldgame/inputs
Content-Type: application/json

{"playerCode": "sit", "input": "Islande"}

###

POST http://localhost:8080/games/oldgame/inputs
Content-Type: application/json

{"playerCode": "amet", "input": "Scandinavie"}

###

POST http://localhost:8080/games/oldgame/inputs
Content-Type: application/json

{"playerCode": "donec", "input": "Grande-Bretagne"}

###

